### ISSUE TITLE
Fails with mysterious error message when untracked files that clash are present

### ISSUE THREAD

**Issue by yuvipanda** [data-8/nbinteract#7] opened 2017-01-24 04:54 UTC
```
[01/24/2017 04:41:47 AM]: INFO -- (USERNAME) From https://github.com/data-8/data8assets
[01/24/2017 04:41:47 AM]: INFO -- (USERNAME)  = [up to date]      gh-pages   -> origin/gh-pages
[01/24/2017 04:41:47 AM]: DEBUG -- Popen(['git', 'merge', '-Xours', 'origin/gh-pages'], cwd=/home/jovyan/data8assets, universal_newlines=False, shell=None)
[01/24/2017 04:41:47 AM]: ERROR -- Cmd('git') failed due to: exit code(128)
  cmdline: git merge -Xours origin/gh-pages
  stderr: 'error: The following untracked working tree files would be overwritten by merge:
	materials/sp17/hw/hw01/hw01_solution.ipynb
Please move or remove them before you can merge.
Aborting'
[01/24/2017 04:41:47 AM]: INFO -- We're in development so we won't chown the dir.
[01/24/2017 04:41:47 AM]: ERROR -- Sent message: {'type': 'ERROR', 'payload': "'str' object has no attribute 'decode'"}
```

**Comment by SaladRaider** [comment] 2017-01-24 05:59
Does this happen when new files are created that don't exist in origin?

**Comment by SaladRaider** [comment] 2017-01-24 06:21
Oh, I see. I just read the conversation on Slack. The issue is that Interact is not displaying clear error messages. I'll try to come up with a fix.

**Comment by SaladRaider** [comment] 2017-01-24 06:47
Ok, this should be fixed now. Interact should not display this mysterious error message, but should show something more readable.

**Comment by ryanlovett** [comment] 2017-01-25 23:07
Committed and fixed in datahub-dev.

**Closed by ryanlovett** 2017-01-25 23:07 UTC
